INSERT INTO departments (department_name)
Values ('Sales'),
    ('IT'),
    ('Legal'),
    ('Engineering'),
    ('Financing');
INSERT INTO roles (title, salary, department_id)
Values ('Sales Head', 50000, 1),
    ('Sales Member', 35000, 1),
    ('IT Technician', 55000, 2),
    ('IT Support', 35000, 2),
    ('Legal Partner', 65000, 3),
    ('Lawyer', 55000, 3),
    ('Legal Intern', 25000, 3),
    ('Senior Engineer', 90000, 4),
    ('Engineer', 50000, 4),
    ('Accountant', 50000, 5),
    ('Accounting Intern', 25000, 5);
INSERT INTO employees (first_name, last_name, role_id, manager_id)
Values ('James', 'Fraser', 1, NULL),
    ('Jack', 'London', 2, 1),
    ('Robert', 'Bruce', 2, 1),
    ('Peter', 'Greenaway', 2, 1),
    ('Derek', 'Jarman', 1, 1),
    ('Paolo', 'Pasolini', 2, 5),
    ('Heathcote', 'Williams', 2, 5),
    ('Sandy', 'Powell', 3, NULL),
    ('Emil', 'Zola', 4, 8),
    ('Sissy', 'Coalpits', 4, 8),
    ('Antoinette', 'Capet', 4, 8),
    ('Samuel', 'Delany', 5, NULL),
    ('Tony', 'Duvert', 5, NULL),
    ('Dennis', 'Cooper', 6, 12),
    ('Monica', 'Bellucci', 6, 12),
    ('Samuel', 'Johnson', 6, 13),
    ('John', 'Dryden', 7, 16),
    ('Alexander', 'Pope', 8, NULL),
    ('Lionel', 'Johnson', 9, 18),
    ('Aubrey', 'Beardsley', 9, 18),
    ('Tulse', 'Luper', 9, 18),
    ('William', 'Morris', 9, 18),
    ('George', 'Shaw', 10, NULL),
    ('Arnold', 'Bennett', 10, 23),
    ('Algernon', 'Blackwood', 10, 23),
    ('Rhoda', 'Broughton', 11, 23),
    ('Hart', 'Crane', 11, 23);